spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/go_together
    username: root
    password: root
    tomcat:
      max-active: 100
    hikari:
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
#  cache:
#    jcache:
#      config: ehcache.xml


  jackson:
#    serialization:
#      write_dates_as_timestamps: false
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: UTC
#    converters:
#      preferred-json-mapper: gson
#    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


jwt:
  secret: NguyenNgocDuy

server:
  port: 8888

app:
  firebase-configuration-file: gotogether-ebbee-firebase-adminsdk-9thii-da644f428a.json
